import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, Minus, HelpCircle } from 'lucide-react';

const faqs = [
  {
    question: "What exactly is Timevora?",
    answer: "Timevora is an emotionally intelligent platform that uses advanced AI to help you explore 'what if' scenarios in your life. It generates believable alternate narratives to provide perspective, emotional closure, or simply a space for reflection."
  },
  {
    question: "Is the simulation accurate?",
    answer: "The simulations are generated by a sophisticated AI model trained on human experiences, but they are fictional. They are intended for reflection and entertainment, not as factual predictions of what would have happened."
  },
  {
    question: "Is my data private?",
    answer: "Yes. We use Firebase for secure authentication. Your personal stories and simulations are private to your account. We do not sell your data to third parties."
  },
  {
    question: "Can I use this for professional advice?",
    answer: "No. Timevora is not a substitute for professional counseling, legal advice, or financial planning. It is a tool for personal reflection and creative exploration."
  },
  {
    question: "How do I get the best results?",
    answer: "The more context you provide about your emotional state and the specific decision point, the more nuanced and resonant the AI's response will be."
  }
];

export const FAQSection: React.FC = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="py-24 px-6 bg-[#0a0502]" id="faq">
      <div className="max-w-3xl mx-auto">
        <div className="text-center mb-16">
          <div className="inline-flex items-center justify-center p-3 bg-[#ff4e00]/10 rounded-2xl mb-6">
            <HelpCircle className="w-6 h-6 text-[#ff4e00]" />
          </div>
          <h2 className="text-4xl font-light text-[#f5f2ed] mb-4">Common Questions</h2>
          <p className="text-[#f5f2ed]/60">Everything you need to know about the TimeShift experience.</p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => (
            <motion.div
              key={index}
              className="border border-white/5 rounded-2xl overflow-hidden bg-[#151619]/50"
            >
              <button
                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                className="w-full p-6 flex items-center justify-between text-left hover:bg-white/5 transition-colors"
              >
                <span className="text-[#f5f2ed] font-medium">{faq.question}</span>
                {openIndex === index ? (
                  <Minus className="w-5 h-5 text-[#ff4e00]" />
                ) : (
                  <Plus className="w-5 h-5 text-white/30" />
                )}
              </button>
              <AnimatePresence>
                {openIndex === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                  >
                    <div className="px-6 pb-6 text-[#f5f2ed]/60 text-sm leading-relaxed">
                      {faq.answer}
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};
