import React from 'react';
import { motion } from 'framer-motion';
import { Shield, FileText, AlertTriangle, X } from 'lucide-react';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  type: 'terms' | 'privacy' | 'disclaimer';
}

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose, type }) => {
  if (!isOpen) return null;

  const content = {
    terms: {
      title: "Terms & Conditions",
      icon: <FileText className="w-6 h-6 text-[#ff4e00]" />,
      sections: [
        {
          heading: "1. Acceptance of Terms",
          text: "By accessing and using Timevora, you agree to be bound by these Terms and Conditions and all applicable laws and regulations."
        },
        {
          heading: "2. Use of Service",
          text: "Timevora provides AI-generated simulations for reflection and entertainment. These simulations are not predictions of reality. You must be at least 18 years old to use this service."
        },
        {
          heading: "3. User Conduct",
          text: "You agree not to use the service for any unlawful purpose or to submit content that is harmful, offensive, or violates the rights of others."
        },
        {
          heading: "4. Intellectual Property",
          text: "The content, features, and functionality of Timevora are owned by us and are protected by international copyright, trademark, and other intellectual property laws."
        }
      ]
    },
    privacy: {
      title: "Privacy Policy",
      icon: <Shield className="w-6 h-6 text-[#ff4e00]" />,
      sections: [
        {
          heading: "1. Information Collection",
          text: "We collect information you provide directly to us, such as when you create an account, use our simulation tools, or contact us for support."
        },
        {
          heading: "2. Use of Information",
          text: "We use the information we collect to provide, maintain, and improve our services, and to communicate with you about your account."
        },
        {
          heading: "3. Data Security",
          text: "We implement reasonable security measures to protect your personal information from unauthorized access or disclosure."
        },
        {
          heading: "4. Third-Party Services",
          text: "We use third-party services like Firebase for authentication and Google AI for simulations. These services have their own privacy policies."
        }
      ]
    },
    disclaimer: {
      title: "Legal Disclaimer",
      icon: <AlertTriangle className="w-6 h-6 text-[#ff4e00]" />,
      sections: [
        {
          heading: "Entertainment Purposes Only",
          text: "Timevora is an experimental AI tool. All simulations, narratives, and outcomes generated are purely fictional and intended for reflection and entertainment purposes only."
        },
        {
          heading: "Not Professional Advice",
          text: "The content generated by Timevora does not constitute professional, medical, legal, or financial advice. Always seek the advice of a qualified professional for such matters."
        },
        {
          heading: "No Guarantee of Accuracy",
          text: "We make no representations or warranties about the accuracy or reliability of the AI-generated content. Use of the service is at your own risk."
        }
      ]
    }
  };

  const current = content[type];

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[150] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm"
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0, y: 20 }}
        animate={{ scale: 1, opacity: 1, y: 0 }}
        className="bg-[#151619] border border-white/10 rounded-3xl w-full max-w-2xl max-h-[80vh] overflow-hidden flex flex-col shadow-2xl"
      >
        <div className="p-6 border-bottom border-white/5 flex items-center justify-between bg-[#1a1b1e]">
          <div className="flex items-center gap-3">
            {current.icon}
            <h2 className="text-xl font-medium text-[#f5f2ed]">{current.title}</h2>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white/5 rounded-full transition-colors">
            <X className="w-5 h-5 text-white/50" />
          </button>
        </div>
        
        <div className="p-8 overflow-y-auto custom-scrollbar">
          <div className="space-y-8">
            {current.sections.map((section, idx) => (
              <div key={idx} className="space-y-3">
                <h3 className="text-[#ff4e00] font-medium text-sm uppercase tracking-wider">{section.heading}</h3>
                <p className="text-[#f5f2ed]/70 leading-relaxed text-sm">{section.text}</p>
              </div>
            ))}
          </div>
          
          <div className="mt-12 pt-8 border-t border-white/5 text-center">
            <p className="text-xs text-white/30 italic">Last Updated: February 27, 2026</p>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
};
